### ISSUE TITLE
Error: 'LicenseWithExceptionSymbol' object has no attribute 'key'

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [aboutcode-org/scancode.io#1719]
There is an issue with `compute_compliance_alert` with license expressions having license exceptions during:
* codebase resource scanning
* package creation, from purldb or usually from detected packages

This is introduced in https://github.com/aboutcode-org/scancode.io/pull/1714/files as `licensing.parse(license_expression, simple=True).symbols` is not enough as `LicenseWithExceptionSymbol` do not have the `key` attribute, but they need to be decomposed into it's symbols which have the `key` attribute. And this is handled through `licensing.license_symbols` 

This is causing the pipeline to fail directly or in some case adds error messages
```
'LicenseWithExceptionSymbol' object has no attribute 'key'

Traceback:
  File "/opt/scancodeio/aboutcode/pipeline/__init__.py", line 199, in execute
    step(self)
    ~~~~^^^^^^
  File "/opt/scancodeio/scanpipe/pipelines/deploy_to_develop.py", line 239, in match_directories_to_purldb
    d2d.match_purldb_directories(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        project=self.project,
        ^^^^^^^^^^^^^^^^^^^^^
        logger=self.log,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/scancodeio/scanpipe/pipes/d2d.py", line 738, in match_purldb_directories
    match_purldb_directory(project, directory)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/scancodeio/scanpipe/pipes/d2d.py", line 595, in match_purldb_directory
    return create_package_from_purldb_data(
        project, [resource], package_data, flag.MATCHED_TO_PURLDB_DIRECTORY
    )
  File "/opt/scancodeio/scanpipe/pipes/d2d.py", line 494, in create_package_from_purldb_data
    package = pipes.update_or_create_package(
        project=project,
        package_data=package_data,
        codebase_resources=resources_qs,
    )
  File "/opt/scancodeio/scanpipe/pipes/__init__.py", line 211, in update_or_create_package
    package = DiscoveredPackage.create_from_data(project, package_data)
```
